<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
    <PackageReference Include="StbTrueTypeSharp" Version="1.26.12" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Artifacts\fonts\a song for jennifer.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\fonts\Able Brush.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\fonts\Blackbold.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\fonts\Brushy Strokes.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\fonts\Ngaco.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\fonts\Ramen Sauce.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\fonts\resilient-essence-demo.regular.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\fonts\Worldstar.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\images\loading01_image.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\images\spinner01_image.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\images\spinner_image.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\photoreal_v0.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\moon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\Ngaco.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>   <None Update="Artifacts\maps\\angaco.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\coastMountain64.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\crater1.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\crater2.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\crater3.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\h.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\h0.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\h1.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\h2.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\h3.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\h4.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\h5.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\h6.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\Heightmap0.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\heightmap19_129.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\heightmap1_129.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\heightmap20_129.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\iceland_heightmap.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map0.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map1.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map10.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map11.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map12.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map4.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map6.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map7.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map8.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\map9.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\photoreal_v1.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\photoreal_v2.raw">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\terrain-heightmap-01.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\maps\\test.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\body-block.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\dying.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\entry.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\Fighting-idle.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\fist-fight.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\hook.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\jump.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\jumping.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\land.fbx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\land.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\looking-around.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\natural-idle.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\punching-bag.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\taking-punch.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\walk-happy.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\walk-standard.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\walk-strafe-left.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\walk-strafe-right.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\walking-backwards.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\anim\walking-backwards2.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\maple_tree.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\tree00.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\tree01.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\trees.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\Tree_1.glb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\Tree_10.glb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\Tree_2.glb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\Tree_3.glb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\Tree_4.glb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\Tree_5.glb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\Tree_6.glb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\Tree_7.glb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\Tree_8.glb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\biomes\Tree_9.glb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\Paladin.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\Stuntman.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\Women.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\invertPass_fragment.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\invertPass_vertex.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\fragment_shader.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\hudFragment_shader.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\lineFragment_shader.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\hudVertex_shader.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\lineVertex_shader.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\shadow_fragment.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\shadow_skinned_vertex.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\shadow_vertex.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\sky_fragment.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\sky_vertex.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\static_vertex.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\vertex_shader.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\gltf_vertex.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\gltf_fragment.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\objects\Xbot.glb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\aerial grass\aerial_grass_rock_diff_4k.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\aerial grass\aerial_grass_rock_disp_4k.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\aerial grass\aerial_grass_rock_rough_4k.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\aerial rock\aerial_rocks_04_diff_4k.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\aerial rock\aerial_rocks_04_disp_4k.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\aerial rock\aerial_rocks_04_rough_4k.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\cliff side\cliff_side_diff_4k.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\cliff side\cliff_side_disp_4k.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\cliff.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\dark_grass.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\floor.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\light_grass.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\moon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\rock.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\snow.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\dirt.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\snow\snow_01_diff_4k.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\snow\snow_01_disp_4k.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\snow\snow_01_rough_4k.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\snow\snow_01_translucent_4k.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>    
    <None Update="Artifacts\Textures\w.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Textures\digital_numbers_atlas_1778438687292.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
