<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Artifacts\Maps\map.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Maps\map.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\fragment_shader.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\lineFragment_shader.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\lineVertex_shader.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\shaders\vertex_shader.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Models\*.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Models\*.OBJ">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Models\*.mtl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Models\*.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Models\*.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Models\*.jpeg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Artifacts\Models\*.tga">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
